name: Terraform Unit Test

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      
    # Install kubectl - will be used later for Istio commands
    - name: Install kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
        
    # Install the AWS CLI to setup kubectl
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      
    - name: 'Terraform Format All Files'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.19
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Link'
      run: echo 'to be implemented'
    - name: 'Terraform Init Dev'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.19
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './env/dev'
        tf_actions_comment: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Validate Dev'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.19
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: './env/dev'
        tf_actions_comment: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Terraform Plan Dev'
      id: 'terraform_plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.19
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './env/dev'
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
