name: Terratest
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out this repo code and tests
      uses: actions/checkout@v2

    - name: Set up Go 1.13 (required for terratest)
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Configure dependencies for test
      run: |
        go mod init "github.com/mitraman/github-action-workshop"
        
    - name: Run terratest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      run: |
        go test -v -timeout 30m
      working-directory: ./test
